<a href="https://colab.research.google.com/github/dunurejoice20/electricity-forecasting./blob/main/notebooks/01_eda_miracle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import zipfile

zip_path = "/content/archive (5).zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
  zip_ref.extractall("/content/electricity_data")

print("Dataset extracted sucessfully!")

Dataset extracted sucessfully!

In [31]:
import os

os.listdir('/content')

['.config', 'electricity_data', 'archive (5).zip', 'sample_data']

In [3]:
import os \

os.listdir("/content/electricity_data")

['household_power_consumption.txt']

In [4]:
import pandas as pd

df = pd.read_csv(
    "/content/electricity_data/household_power_consumption.txt",
    sep=";",
    na_values="?"
)

df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   object
 1   Time                   object
 2   Global_active_power    float64
 3   Global_reactive_power  float64
 4   Voltage                float64
 5   Global_intensity       float64
 6   Sub_metering_1         float64
 7   Sub_metering_2         float64
 8   Sub_metering_3         float64
dtypes: float64(7), object(2)
memory usage: 142.5+ MB

In [6]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.dtypes

Date                      object
Time                      object
Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
Sub_metering_2           float64
Sub_metering_3           float64
dtype: object

In [9]:
df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)

In [10]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
dtype: object

In [11]:
df['Time'] = pd.to_datetime(df["Time"], format='%H:%M:%S').dt.time

In [12]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
dtype: object

In [13]:
df['Datetime'] = pd.to_datetime(
    df['Date'].dt.strftime('%Y-%m-%d') +  '' + df['Time'].astype(str),
    errors='coerce'

)

/tmp/ipykernel_694/1851200061.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Datetime'] = pd.to_datetime(

In [14]:
df[['Date', 'Time', 'Datetime']].head()

        Date      Time Datetime
0 2006-12-16  17:24:00      NaT
1 2006-12-16  17:25:00      NaT
2 2006-12-16  17:26:00      NaT
3 2006-12-16  17:27:00      NaT
4 2006-12-16  17:28:00      NaT

In [15]:
df['Hour'] = pd.to_datetime(
    df['Time'],
    format='%H:%M:%S'
).dt.hour

In [16]:
df[['Time', 'Hour', ]].head()

       Time  Hour
0  17:24:00    17
1  17:25:00    17
2  17:26:00    17
3  17:27:00    17
4  17:28:00    17

In [17]:
df['Day'] = df['Date'].dt.day

In [18]:
df[['Date', 'Day']].head()

        Date  Day
0 2006-12-16   16
1 2006-12-16   16
2 2006-12-16   16
3 2006-12-16   16
4 2006-12-16   16

In [19]:
df['Month'] = df['Date'].dt.month

In [20]:
df[['Date', 'Month']].head()

        Date  Month
0 2006-12-16     12
1 2006-12-16     12
2 2006-12-16     12
3 2006-12-16     12
4 2006-12-16     12

In [21]:
df['Day_of_week'] = df['Date'].dt.dayofweek

In [22]:
df[['Date', 'Day_of_week']].head()

        Date  Day_of_week
0 2006-12-16            5
1 2006-12-16            5
2 2006-12-16            5
3 2006-12-16            5
4 2006-12-16            5

In [23]:
df.isnull().sum()

Date                           0
Time                           0
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
Datetime                 2075259
Hour                           0
Day                            0
Month                          0
Day_of_week                    0
dtype: int64

In [24]:
df['Month'] = df['Date'].dt.month

In [25]:
df[['Date', 'Month']].head()

        Date  Month
0 2006-12-16     12
1 2006-12-16     12
2 2006-12-16     12
3 2006-12-16     12
4 2006-12-16     12

In [26]:
df['DayOfWeek'] = df['Date'].dt.dayofweek

In [27]:
df[['Date', 'DayOfWeek']].head()

        Date  DayOfWeek
0 2006-12-16          5
1 2006-12-16          5
2 2006-12-16          5
3 2006-12-16          5
4 2006-12-16          5

In [28]:
df.isnull().sum()

Date                           0
Time                           0
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
Datetime                 2075259
Hour                           0
Day                            0
Month                          0
Day_of_week                    0
DayOfWeek                      0
dtype: int64

In [29]:
df.columns.tolist()

['Date',
 'Time',
 'Global_active_power',
 'Global_reactive_power',
 'Voltage',
 'Global_intensity',
 'Sub_metering_1',
 'Sub_metering_2',
 'Sub_metering_3',
 'Datetime',
 'Hour',
 'Day',
 'Month',
 'Day_of_week',
 'DayOfWeek']

In [33]:
print(df.columns.tolist())

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Datetime', 'Hour', 'Day', 'Month', 'Day_of_week', 'DayOfWeek']

In [34]:
print(len(df.columns))

15

In [35]:
df.shape

(2075259, 15)

In [36]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime,Hour,Day,Month,Day_of_week,DayOfWeek
0,2006-12-16,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,NaT,17,16,12,5,5
1,2006-12-16,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,NaT,17,16,12,5,5
2,2006-12-16,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,NaT,17,16,12,5,5
3,2006-12-16,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,NaT,17,16,12,5,5
4,2006-12-16,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,NaT,17,16,12,5,5

In [37]:
df.columns[df.columns.duplicated()]

Index([], dtype='object')

In [40]:
print(df[['Date', 'Hour', 'Month', 'DayOfWeek']].head(10))

        Date  Hour  Month  DayOfWeek
0 2006-12-16    17     12          5
1 2006-12-16    17     12          5
2 2006-12-16    17     12          5
3 2006-12-16    17     12          5
4 2006-12-16    17     12          5
5 2006-12-16    17     12          5
6 2006-12-16    17     12          5
7 2006-12-16    17     12          5
8 2006-12-16    17     12          5
9 2006-12-16    17     12          5

In [41]:
print(df.columns.tolist())

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Datetime', 'Hour', 'Day', 'Month', 'Day_of_week', 'DayOfWeek']

In [42]:
df.columns[df.columns.duplicated()]

Index([], dtype='object')

In [44]:
for i, col in enumerate(df.columns):
  print(i, repr(col))

0 'Date'
1 'Time'
2 'Global_active_power'
3 'Global_reactive_power'
4 'Voltage'
5 'Global_intensity'
6 'Sub_metering_1'
7 'Sub_metering_2'
8 'Sub_metering_3'
9 'Datetime'
10 'Hour'
11 'Day'
12 'Month'
13 'Day_of_week'
14 'DayOfWeek'

In [43]:
df[['Day_of_week', 'DayOfWeek']].head()

   Day_of_week  DayOfWeek
0            5          5
1            5          5
2            5          5
3            5          5
4            5          5

In [45]:
df = df.drop(columns=['DayOfWeek'])

In [46]:
df.columns.tolist()

['Date',
 'Time',
 'Global_active_power',
 'Global_reactive_power',
 'Voltage',
 'Global_intensity',
 'Sub_metering_1',
 'Sub_metering_2',
 'Sub_metering_3',
 'Datetime',
 'Hour',
 'Day',
 'Month',
 'Day_of_week']

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df.isnull().sum()

Date                           0
Time                           0
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
Datetime                 2075259
Hour                           0
Day                            0
Month                          0
Day_of_week                    0
dtype: int64

In [49]:
df.shape

(2075259, 14)

In [50]:
df.isnull().mean() * 100

Date                       0.000000
Time                       0.000000
Global_active_power        1.251844
Global_reactive_power      1.251844
Voltage                    1.251844
Global_intensity           1.251844
Sub_metering_1             1.251844
Sub_metering_2             1.251844
Sub_metering_3             1.251844
Datetime                 100.000000
Hour                       0.000000
Day                        0.000000
Month                      0.000000
Day_of_week                0.000000
dtype: float64

In [52]:
df = df.drop(columns=['Datetime'])

In [53]:
df.shape

(2075259, 13)

In [54]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
Hour                              int32
Day                               int32
Month                             int32
Day_of_week                       int32
dtype: object

In [55]:
df['Time'].head()

0    17:24:00
1    17:25:00
2    17:26:00
3    17:27:00
4    17:28:00
Name: Time, dtype: object

In [56]:
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.time

In [57]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
Hour                              int32
Day                               int32
Month                             int32
Day_of_week                       int32
dtype: object

In [58]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
Hour                         0
Day                          0
Month                        0
Day_of_week                  0
dtype: int64

In [59]:
df[df['Global_active_power'].isnull()].head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Hour,Day,Month,Day_of_week
6839,2006-12-21,11:23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,21,12,3
6840,2006-12-21,11:24:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,21,12,3
19724,2006-12-30,10:08:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,30,12,5
19725,2006-12-30,10:09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,30,12,5
41832,2007-01-14,18:36:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,14,1,6

In [60]:
measurement_cols = [
    'Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3',
]

df[measurement_cols].isnull().all(axis=1).sum()

np.int64(25979)

In [61]:
df = df.dropna(subset=measurement_cols)

In [62]:
df.shape

(2049280, 13)

In [63]:
df.isnull().sum()

Date                     0
Time                     0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
Hour                     0
Day                      0
Month                    0
Day_of_week              0
dtype: int64

In [64]:
df.duplicated().sum()

np.int64(0)