<a href="https://colab.research.google.com/github/dunurejoice20/electricity-forecasting./blob/main/notebooks/Jay's_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv(
    "household_power_consumption.txt",
    sep=";",
    na_values="?"
)

df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   object
 1   Time                   object
 2   Global_active_power    float64
 3   Global_reactive_power  float64
 4   Voltage                float64
 5   Global_intensity       float64
 6   Sub_metering_1         float64
 7   Sub_metering_2         float64
 8   Sub_metering_3         float64
dtypes: float64(7), object(2)
memory usage: 142.5+ MB

In [4]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.dtypes

Date                      object
Time                      object
Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
Sub_metering_2           float64
Sub_metering_3           float64
dtype: object

In [7]:
df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)

In [8]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
dtype: object

In [9]:
df['Time'] = pd.to_datetime(df["Time"], format='%H:%M:%S').dt.time

In [10]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
dtype: object

In [11]:
df['Datetime'] = pd.to_datetime(
    df['Date'].dt.strftime('%Y-%m-%d') +  '' + df['Time'].astype(str),
    errors='coerce'

)

/tmp/ipykernel_1191/1851200061.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Datetime'] = pd.to_datetime(

In [12]:
df[['Date', 'Time', 'Datetime']].head()

        Date      Time Datetime
0 2006-12-16  17:24:00      NaT
1 2006-12-16  17:25:00      NaT
2 2006-12-16  17:26:00      NaT
3 2006-12-16  17:27:00      NaT
4 2006-12-16  17:28:00      NaT

In [13]:
df['Hour'] = pd.to_datetime(
    df['Time'],
    format='%H:%M:%S'
).dt.hour

In [14]:
df[['Time', 'Hour', ]].head()

       Time  Hour
0  17:24:00    17
1  17:25:00    17
2  17:26:00    17
3  17:27:00    17
4  17:28:00    17

In [15]:
df['Day'] = df['Date'].dt.day

In [16]:
df[['Date', 'Day']].head()

        Date  Day
0 2006-12-16   16
1 2006-12-16   16
2 2006-12-16   16
3 2006-12-16   16
4 2006-12-16   16

In [17]:
df['Month'] = df['Date'].dt.month

In [18]:
df[['Date', 'Month']].head()

        Date  Month
0 2006-12-16     12
1 2006-12-16     12
2 2006-12-16     12
3 2006-12-16     12
4 2006-12-16     12

In [19]:
df['Day_of_week'] = df['Date'].dt.dayofweek

In [20]:
df[['Date', 'Day_of_week']].head()

        Date  Day_of_week
0 2006-12-16            5
1 2006-12-16            5
2 2006-12-16            5
3 2006-12-16            5
4 2006-12-16            5

In [21]:
df.isnull().sum()

Date                           0
Time                           0
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
Datetime                 2075259
Hour                           0
Day                            0
Month                          0
Day_of_week                    0
dtype: int64

In [22]:
df['Month'] = df['Date'].dt.month

In [23]:
df[['Date', 'Month']].head()

        Date  Month
0 2006-12-16     12
1 2006-12-16     12
2 2006-12-16     12
3 2006-12-16     12
4 2006-12-16     12

In [24]:
df['DayOfWeek'] = df['Date'].dt.dayofweek

In [25]:
df[['Date', 'DayOfWeek']].head()

        Date  DayOfWeek
0 2006-12-16          5
1 2006-12-16          5
2 2006-12-16          5
3 2006-12-16          5
4 2006-12-16          5

In [26]:
df.isnull().sum()

Date                           0
Time                           0
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
Datetime                 2075259
Hour                           0
Day                            0
Month                          0
Day_of_week                    0
DayOfWeek                      0
dtype: int64

In [27]:
df.columns.tolist()

['Date',
 'Time',
 'Global_active_power',
 'Global_reactive_power',
 'Voltage',
 'Global_intensity',
 'Sub_metering_1',
 'Sub_metering_2',
 'Sub_metering_3',
 'Datetime',
 'Hour',
 'Day',
 'Month',
 'Day_of_week',
 'DayOfWeek']

In [28]:
print(df.columns.tolist())

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Datetime', 'Hour', 'Day', 'Month', 'Day_of_week', 'DayOfWeek']

In [29]:
print(len(df.columns))

15

In [30]:
df.shape

(2075259, 15)

In [31]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime,Hour,Day,Month,Day_of_week,DayOfWeek
0,2006-12-16,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,NaT,17,16,12,5,5
1,2006-12-16,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,NaT,17,16,12,5,5
2,2006-12-16,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,NaT,17,16,12,5,5
3,2006-12-16,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,NaT,17,16,12,5,5
4,2006-12-16,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,NaT,17,16,12,5,5

In [32]:
df.columns[df.columns.duplicated()]

Index([], dtype='object')

In [33]:
print(df[['Date', 'Hour', 'Month', 'DayOfWeek']].head(10))

        Date  Hour  Month  DayOfWeek
0 2006-12-16    17     12          5
1 2006-12-16    17     12          5
2 2006-12-16    17     12          5
3 2006-12-16    17     12          5
4 2006-12-16    17     12          5
5 2006-12-16    17     12          5
6 2006-12-16    17     12          5
7 2006-12-16    17     12          5
8 2006-12-16    17     12          5
9 2006-12-16    17     12          5

In [34]:
print(df.columns.tolist())

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Datetime', 'Hour', 'Day', 'Month', 'Day_of_week', 'DayOfWeek']

In [35]:
df.columns[df.columns.duplicated()]

Index([], dtype='object')

In [36]:
for i, col in enumerate(df.columns):
  print(i, repr(col))

0 'Date'
1 'Time'
2 'Global_active_power'
3 'Global_reactive_power'
4 'Voltage'
5 'Global_intensity'
6 'Sub_metering_1'
7 'Sub_metering_2'
8 'Sub_metering_3'
9 'Datetime'
10 'Hour'
11 'Day'
12 'Month'
13 'Day_of_week'
14 'DayOfWeek'

In [37]:
df[['Day_of_week', 'DayOfWeek']].head()

   Day_of_week  DayOfWeek
0            5          5
1            5          5
2            5          5
3            5          5
4            5          5

In [38]:
df = df.drop(columns=['DayOfWeek'])

In [39]:
df.columns.tolist()

['Date',
 'Time',
 'Global_active_power',
 'Global_reactive_power',
 'Voltage',
 'Global_intensity',
 'Sub_metering_1',
 'Sub_metering_2',
 'Sub_metering_3',
 'Datetime',
 'Hour',
 'Day',
 'Month',
 'Day_of_week']

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.isnull().sum()

Date                           0
Time                           0
Global_active_power        25979
Global_reactive_power      25979
Voltage                    25979
Global_intensity           25979
Sub_metering_1             25979
Sub_metering_2             25979
Sub_metering_3             25979
Datetime                 2075259
Hour                           0
Day                            0
Month                          0
Day_of_week                    0
dtype: int64

In [42]:
df.shape

(2075259, 14)

In [43]:
df.isnull().mean() * 100

Date                       0.000000
Time                       0.000000
Global_active_power        1.251844
Global_reactive_power      1.251844
Voltage                    1.251844
Global_intensity           1.251844
Sub_metering_1             1.251844
Sub_metering_2             1.251844
Sub_metering_3             1.251844
Datetime                 100.000000
Hour                       0.000000
Day                        0.000000
Month                      0.000000
Day_of_week                0.000000
dtype: float64

In [44]:
df = df.drop(columns=['Datetime'])

In [45]:
df.shape

(2075259, 13)

In [46]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
Hour                              int32
Day                               int32
Month                             int32
Day_of_week                       int32
dtype: object

In [47]:
df['Time'].head()

0    17:24:00
1    17:25:00
2    17:26:00
3    17:27:00
4    17:28:00
Name: Time, dtype: object

In [48]:
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.time

In [49]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
Hour                              int32
Day                               int32
Month                             int32
Day_of_week                       int32
dtype: object

In [50]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
Hour                         0
Day                          0
Month                        0
Day_of_week                  0
dtype: int64

In [51]:
df[df['Global_active_power'].isnull()].head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Hour,Day,Month,Day_of_week
6839,2006-12-21,11:23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,21,12,3
6840,2006-12-21,11:24:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,21,12,3
19724,2006-12-30,10:08:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,30,12,5
19725,2006-12-30,10:09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,30,12,5
41832,2007-01-14,18:36:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,14,1,6

In [52]:
measurement_cols = [
    'Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3',
]

df[measurement_cols].isnull().all(axis=1).sum()

np.int64(25979)

In [53]:
df = df.dropna(subset=measurement_cols)

In [54]:
df.shape

(2049280, 13)

In [55]:
df.isnull().sum()

Date                     0
Time                     0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
Hour                     0
Day                      0
Month                    0
Day_of_week              0
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
Hour                              int32
Day                               int32
Month                             int32
Day_of_week                       int32
dtype: object

In [58]:
df.describe()

,Date,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Hour,Day,Month,Day_of_week
count,2049280,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,2008-12-01 13:00:00.309181952,1.091615e+00,1.237145e-01,2.408399e+02,4.627759e+00,1.121923e+00,1.298520e+00,6.458447e+00,1.150391e+01,1.571245e+01,6.454433e+00,2.989276e+00
min,2006-12-16 00:00:00,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00
25%,2007-12-10 00:00:00,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,8.000000e+00,3.000000e+00,1.000000e+00
50%,2008-11-30 00:00:00,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.200000e+01,1.600000e+01,6.000000e+00,3.000000e+00
75%,2009-11-23 00:00:00,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,0.000000e+00,1.000000e+00,1.700000e+01,1.800000e+01,2.300000e+01,9.000000e+00,5.000000e+00
max,2010-11-26 00:00:00,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.800000e+01,8.000000e+01,3.100000e+01,2.300000e+01,3.100000e+01,1.200000e+01,6.000000e+00
std,NaN,1.057294e+00,1.127220e-01,3.239987e+00,4.444396e+00,6.153031e+00,5.822026e+00,8.437154e+00,6.925189e+00,8.801670e+00,3.423209e+00,1.997633e+00

In [59]:
df[['Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3',]].min()

Global_active_power        0.076
Global_reactive_power      0.000
Voltage                  223.200
Global_intensity           0.200
Sub_metering_1             0.000
Sub_metering_2             0.000
Sub_metering_3             0.000
dtype: float64

In [60]:
df[['Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3']].max()

Global_active_power       11.122
Global_reactive_power      1.390
Voltage                  254.150
Global_intensity          48.400
Sub_metering_1            88.000
Sub_metering_2            80.000
Sub_metering_3            31.000
dtype: float64

In [61]:
df['Date'].min(), df['Date'].max()

(Timestamp('2006-12-16 00:00:00'), Timestamp('2010-11-26 00:00:00'))

In [62]:
df['Date'].is_monotonic_increasing

True

In [63]:
print("Hours below 0:", (df['Hour'] < 0).sum())
print("Hours above 23:", (df['Hour'] > 23).sum())

Hours below 0: 0
Hours above 23: 0

In [64]:
print("Days below 1:", (df['Day'] < 1).sum())
print("Days above 31:", (df['Day'] > 31).sum())

Days below 1: 0
Days above 31: 0

In [65]:
print("Months below 1:", (df['Month'] < 1).sum())
print("Months above 12:", (df['Month'] > 12).sum())

Months below 1: 0
Months above 12: 0

In [66]:
print("Days_of_week below 0:", (df['Day_of_week'] < 0).sum())
print("Days_of_week above 6:", (df['Day_of_week'] > 6).sum())

Days_of_week below 0: 0
Days_of_week above 6: 0

In [67]:
cols = [
    'Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3',
]

df[cols].lt(0).sum()

Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64

In [68]:
df.shape

(2049280, 13)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2049280 entries, 0 to 2075258
Data columns (total 13 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   datetime64[ns]
 1   Time                   object
 2   Global_active_power    float64
 3   Global_reactive_power  float64
 4   Voltage                float64
 5   Global_intensity       float64
 6   Sub_metering_1         float64
 7   Sub_metering_2         float64
 8   Sub_metering_3         float64
 9   Hour                   int32
 10  Day                    int32
 11  Month                  int32
 12  Day_of_week            int32
dtypes: datetime64[ns](1), float64(7), int32(4), object(1)
memory usage: 187.6+ MB

In [70]:
df["datetime"] = df["Date"] + pd.to_timedelta(df["Time"].astype(str))
df = df.set_index("datetime").sort_index()

hourly = df["Global_active_power"].resample("h").mean()
print("Missing hours:", hourly.isna().sum())

hourly = hourly.interpolate(limit=6)   # fills short gaps only
print("Still missing:", hourly.isna().sum())

hourly.to_frame().reset_index().to_csv("clean_hourly.csv", index=False)

Missing hours: 421
Still missing: 378

Jay Below

In [84]:
#importing needed libraries

import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Scikit-learn version:", sklearn.__version__)
print("TensorFlow version:", tf.__version__)

Pandas version: 2.2.3
NumPy version: 2.1.3
Scikit-learn version: 1.6.1
TensorFlow version: 2.21.0

In [85]:
import pandas as pd



print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (2049280, 13)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Hour,Day,Month,Day_of_week
datetime,,,,,,,,,,,,,
2006-12-16 17:24:00,2006-12-16,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,17,16,12,5
2006-12-16 17:25:00,2006-12-16,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,17,16,12,5
2006-12-16 17:26:00,2006-12-16,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,17,16,12,5
2006-12-16 17:27:00,2006-12-16,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,17,16,12,5
2006-12-16 17:28:00,2006-12-16,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,17,16,12,5